### ISSUE TITLE
[Cleanup] Refactor code to remove template module and move components to main module

### ISSUE THREAD

**Issue by Utkar5hM** [IRIS-NITK/Staging-Server#3]
The template module is no longer needed after the implementation of the repository module. However, both the gitlab_social and the repository module still use some components that are defined in the template module. These components should be moved to the main module to avoid unnecessary dependencies and improve code organization.

The functions that are used by the repository module and are defined in the gitlab_social module should also be moved to the main module, as they are not specific to the gitlab_social functionality.

The template module should be deleted from the repository after the refactoring is done.

### Tasks:
- [x] The template module is removed from the repository
- [x] The components that are used by the gitlab_social and the repository module are moved to the main module
- [x] The functions that are used by the repository module and are defined in the gitlab_social module are moved to the main module
- [ ] The code is tested and works as expected

**Comment by jyothiram266** [comment]
assign it to me. i want to contribute..

**Comment by Utkar5hM** [comment]
Merged off, Thanks for the contribution @jyothiram266.

**Comment by Utkar5hM** [comment]
added missing delete default branch func directly to main branch under commit [f227a07](https://github.com/IRIS-NITK/Staging-Server/commit/f227a070e31cac91c3f796fbe0e545843e03b86c)
